services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: vendormap-dev:latest
    container_name: vendormap-dev
    volumes:
      - ../:/workspace:cached
      - node_modules:/workspace/node_modules
      - back-end-node-modules:/workspace/back-end/node_modules
      - front-end-node-modules:/workspace/front-end/node_modules
    working_dir: /workspace
    command: sleep infinity
    environment:
      - NODE_ENV=development
    networks:
      - vendormap-network

  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    image: vendormap-dev:latest
    container_name: vendormap-backend
    volumes:
      - ../back-end:/workspace/back-end:cached
      - back-end-node-modules:/workspace/back-end/node_modules
    working_dir: /workspace/back-end
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NODE_ENV=development
    networks:
      - vendormap-network
    depends_on:
      - devcontainer
    develop:
      watch:
        - action: sync
          path: .src/server.ts
          ignore: 
            - node_modules
        - action: rebuild
          path: package.json
        

  front-end:
    build:
      context: .
      dockerfile: Dockerfile
    image: vendormap-dev:latest
    container_name: vendormap-frontend
    volumes:
      - ../front-end:/workspace/front-end:cached
      - front-end-node-modules:/workspace/front-end/node_modules
    working_dir: /workspace/front-end
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    networks:
      - vendormap-network
    depends_on:
      - devcontainer

volumes:
  node_modules:
  back-end-node-modules:
  front-end-node-modules:

networks:
  vendormap-network:
    driver: bridge
